name: lando-wordpress-skeleton
recipe: wordpress
config:
  via: nginx
  php: 7.4
  webroot: wordpress
  database: mariadb
  xdebug: true
  config:
    php: .lando/php.ini
    database: .lando/mysql.cnf
    vhosts: .lando/nginx.conf
services:
  rediscache:
    type: redis
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
  appserver:
    overrides:
      environment:
        # Make this environment variable empty or else runtime xdebug mode change will not work
        XDEBUG_MODE: ''
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=appserver"
        PROFILER_OUTPUT_DIR: "profiler-output" # If changing this value, change in .gitignore also
      volumes:
        - '.lando/wp-cli.yml:/wp-cli.yml'
        - './mu-plugins:/app/wordpress/wp-content/mu-plugins'
        - './plugins:/app/wordpress/wp-content/plugins'
        - './rt-config:/app/wordpress/wp-content/rt-config'
        - './themes:/app/wordpress/wp-content/themes'
        - './uploads:/app/wordpress/wp-content/uploads'
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
    build:
      - wp core download --force --skip-content
    run:
      - sleep 2 # For some reason, we have to wait at least a second till database is up.
      - | # Create WordPress config file and add necessary constants and custom config
        wp config create --dbhost=database --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbprefix=wp_ --force --extra-php <<PHP
        if ( file_exists( __DIR__ . '/wp-content/rt-config/rt-config.php' ) ) {
          require_once( __DIR__ . '/wp-content/rt-config/rt-config.php' );
        }
        PHP
      - wp config set WP_DEBUG true --raw
      - wp config set WP_DEBUG_LOG true --raw
      - wp config set WP_DEBUG_DISPLAY false --raw
      - wp config set AUTOMATIC_UPDATER_DISABLED true --raw
      - wp config set DISALLOW_FILE_EDIT true --raw
      - wp config set WP_ENVIRONMENT_TYPE 'local'
      - wp config set WP_REDIS_HOST rediscache
      - | # Let's check if WordPress is not installed, then install it
        if ! wp core is-installed; then
          wp core install --url=https://$LANDO_APP_NAME.$LANDO_DOMAIN \
            --title=$LANDO_APP_NAME \
            --admin_user=rtcamp \
            --admin_password=goodwork \
            --admin_email=lando@rtcamp.com \
            --skip-email
          wp theme install --activate twentytwentyone
          wp plugin install --activate redis-cache
          wp redis enable
        fi
tooling:
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
  node:
    service: appserver
  npm:
    service: appserver